import re

FILLER_PATTERNS = [
    r"\byou know\b",
    r"\blike\b",
    r"\bum\b",
    r"\buh\b",
]

def _count(pattern: str, text: str) -> int:
    return len(re.findall(pattern, text, flags=re.IGNORECASE))

def analyze_transcript_heuristic(transcript_md: str) -> str:
    t = transcript_md

    issues = []
    lower = t.lower()

    filler_total = sum(_count(p, t) for p in FILLER_PATTERNS)
    if filler_total >= 6:
        issues.append(f"Excessive filler words detected. Count {filler_total}. Example keyword: you know.")

    if "wednesday morning" in lower and "wednesday afternoon" in lower:
        issues.append("Scheduling contradiction detected. Patient asked Wednesday morning but agent later references Wednesday afternoon.")

    if re.search(r"(bye|goodbye).*(bye|goodbye).*(bye|goodbye)", lower, flags=re.IGNORECASE | re.DOTALL):
        issues.append("Likely looping goodbye detected. Agent repeats goodbye phrases multiple times.")

    if "refill" in lower and ("bring your prescription" in lower or "bring prescription" in lower):
        issues.append("Possible incorrect refill workflow. Agent suggests bringing a prescription during a phone refill request.")

    if "schedule is an appointment" in lower:
        issues.append("Incoherent or low quality response detected in early scheduling turn.")

    if not issues:
        issues.append("No obvious heuristic issues detected. Consider enabling LLM based QA for deeper checks.")

    out = []
    out.append("# Bug Report")
    out.append("")
    out.append("Generated by heuristic QA fallback.")
    out.append("")
    out.append("## Issues")
    out.append("")
    for i, x in enumerate(issues, start=1):
        out.append(f"{i}. {x}")
    out.append("")
    return "\n".join(out)